version: '3'
services:

    famous_quote_quiz_redis:
        container_name: famous_quote_quiz_redis
        image: redis:6-alpine
        volumes:
            - redis:/data
        networks:
            - localhost

    famous_quote_quiz:
        container_name: famous_quote_quiz
        build: .
#        user: ${CURRENT_UID}
        volumes:
            - .:/var/www/
            - .docker/php.ini:/usr/local/etc/php/conf.d/php.ini
#            - .docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#        expose:
#            - 9003
        ports:
            - "29082:80"
        networks:
            - localhost

networks:
    localhost:
        external: true

volumes:
    redis:
        driver: local
